services:
  - type: web
    name: mvp-store
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py create  # or reset during dev
    startCommand: gunicorn 'app:create_app()'
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
